services:
  directus:
    build:
      context: ./directus
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=debug
      # accounnt
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - ADMIN_TOKEN
      # general
      - PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
      # database
      - DB_CLIENT=pg
      - DB_CONNECTION_STRING
      # security
      - KEY=${DIRECTUS_KEY}
      - ACCESS_TOKEN_TTL=1440m
      - SECRET=${DIRECTUS_SECRET}
      - REFRESH_TOKEN_TTL=1d
      - REFRESH_TOKEN_COOKIE_SECURE=true
      - REFRESH_TOKEN_COOKIE_SAME_SITE=strict
      - REFRESH_TOKEN_COOKIE_NAME=directus_refresh_token
      - PASSWORD_RESET_URL_ALLOW_LIST=${DIRECTUS_PASSWORD_RESET_URL_ALLOW_LIST}
      # cors
      - CORS_ENABLED=true
      - CORS_ORIGIN=true
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,device
      # redis
      - REDIS
      # rate limiting
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_STORE=redis
      # cache
      - CACHE_ENABLED=true
      - CACHE_STORE=redis
      - CACHE_AUTO_PURGE=true
      - CACHE_SYSTEM_TTL=5m
      - CACHE_SKIP_ALLOWED=true
      # file storage
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY
      - STORAGE_S3_SECRET
      - STORAGE_S3_BUCKET
      - STORAGE_S3_ENDPOINT
      - STORAGE_S3_REGION
      - STORAGE_S3_ROOT
      - STORAGE_S3_FORCE_PATH_STYLE=false
      # telemetry
      - TELEMETRY=false
      # websocket
      - WEBSOCKETS_ENABLED=true
      - WEBSOCKETS_HEARTBEAT_ENABLED=true
      - WEBSOCKETS_HEARTBEAT_PERIOD=30
      - WEBSOCKETS_REST_PATH=/websocket
      - WEBSOCKETS_REST_CONN_LIMIT=Infinity
      - WEBSOCKETS_REST_AUTH=handshake
      - WEBSOCKETS_REST_AUTH_TIMEOUT=30
      - WEBSOCKETS_GRAPHQL_ENABLED=false
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        VITE_DIRECTUS_PUBLIC_URL: ${VITE_DIRECTUS_PUBLIC_URL}
        VITE_ACCESS_TOKEN_KEY: token
    ports:
      - "80:80"
    depends_on:
      - directus
    volumes:
      - "./server/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped
