branch-defaults:
  default:
    environment: atrbpn-cbt-env
    group_suffix: null
  main:
    environment: atrbpn-cbt-env
global:
  application_name: atrbpn-cbt
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
