version: "3"

services:
  minio-init:
    image: minio/mc:latest
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    restart: no
    entrypoint: >
      sh -c "
      mc alias set myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      mc mb myminio/atrbpn-cbt"
    networks:
      - storage_network
      
networks:
  storage_network:
    name: storage_network
    external: true
