version: "3"

services:
  minio:
    build:
      context: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio/data:/data"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    restart: unless-stopped
    networks:
      - storage_network

  postgis:
    build:
      context: postgis
    ports:
      - "5433:5432"
    volumes:
      - "./postgis/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    networks:
      - storage_network

networks:
  storage_network:
    name: storage_network
    external: false
